//
//  ChatWorker.swift
//  nafta.messenger.ios
//
//  Created by Yevhen Velizhenkov on 10/12/17.
//  Copyright (c) 2017 Yevhen Velizhenkov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ChatWorker
{
  func doSomeWork()
  {
  }
}
