//
//  ChatInteractor.swift
//  nafta.messenger.ios
//
//  Created by Yevhen Velizhenkov on 10/12/17.
//  Copyright (c) 2017 Yevhen Velizhenkov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatBusinessLogic
{
  func doSomething(request: Chat.FetchChat.Request)
}

protocol ChatDataStore
{
  //var name: String { get set }
}

class ChatInteractor: ChatBusinessLogic, ChatDataStore
{
  var presenter: ChatPresentationLogic?
  var worker: ChatWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Chat.FetchChat.Request)
  {
    worker = ChatWorker()
    worker?.doSomeWork()
    
    let response = Chat.FetchChat.Response()
    presenter?.presentSomething(response: response)
  }
}
