target 'nafta.messenger.ios' do
  use_frameworks!
  pod 'SwiftLint'
  pod 'QMChatViewController'
  pod 'ChameleonFramework'
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'AlamofireNetworkActivityLogger'
end
