target 'nafta.messenger.ios' do
  use_frameworks!
  pod 'SwiftLint'
  pod 'QMChatViewController'
  pod 'ChameleonFramework'
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityLogger'
  pod 'PromiseKit'
  pod 'PromiseKit/Alamofire'
end

target 'nafta.messenger.iosTests' do
  inherit! :search_paths
  use_frameworks!
  pod 'SwiftLint'
  pod 'QMChatViewController'
  pod 'ChameleonFramework'
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityLogger'
  pod 'PromiseKit'
  pod 'PromiseKit/Alamofire'
end
