//
//  ChatListInteractor.swift
//  nafta.messenger.ios
//
//  Created by Yevhen Velizhenkov on 10/16/17.
//  Copyright (c) 2017 Yevhen Velizhenkov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatListBusinessLogic
{
  func doSomething(request: ChatList.Something.Request)
}

protocol ChatListDataStore
{
  //var name: String { get set }
}

class ChatListInteractor: ChatListBusinessLogic, ChatListDataStore
{
  var presenter: ChatListPresentationLogic?
  var worker: ChatListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ChatList.Something.Request)
  {
    worker = ChatListWorker()
    worker?.doSomeWork()
    
    let response = ChatList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
